package cmd

import (
	"fmt"
	"log"
	"os/exec"
	"time"

	"github.com/spf13/cobra"
)

// branchCmd represents the branch command
var branchCmd = &cobra.Command{
	Use:     "branch [NAME]",
	Aliases: []string{"b"},
	Short:   "Start new branch from 'master'",
	Long: `'git op branch [NAME]' creates branch from 'master' named 'NAME'

When 'NAME' is ommitted, it autogenerated like '2019-05-26-13-09'.`,
	Args: cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		var branch = time.Now().Format("2006-01-02-15-04")
		if len(args) > 0 {
			branch = args[0]
		}
		out, err := exec.Command("git", "branch", branch, "master").CombinedOutput()
		err = nil
		fmt.Printf("%s\n", out)
		out, err = exec.Command("git", "checkout", branch).CombinedOutput()
		if err != nil {
			log.Fatal(fmt.Sprintf("%s", out))
		}
		fmt.Printf("%s\n", out)
	},
}

func init() {
	rootCmd.AddCommand(branchCmd)
}
